apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 356192475173.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:latest
        ports:
          - containerPort: 80

