apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 726725565829.dkr.ecr.us-east-1.amazonaws.com/fedhr-repo-backend:latest
        ports:
          - containerPort: 80

